In [20]:
import numpy as np
import random
from tqdm import tqdm

In [2]:
# CONFIG
ATLAS_EMBEDDINGS = "/mnt/nas1/atlas_data/benchmarking/atlas.npy"
QUERY_INDS = "/mnt/nas1/atlas_data/benchmarking/query_ind.npy"
QUERY_VECS = "/mnt/nas1/atlas_data/benchmarking/query_vec.npy"
BASE_ATLAS = "/mnt/nas1/atlas_data/benchmarking/base_atlas.npy"

QUERY_VECS_TEST = "/mnt/nas1/atlas_data/benchmarking/query_vec_test.npy"
QUERY_INDS_TEST = "/mnt/nas1/atlas_data/benchmarking/query_ind_test.npy"
BASE_ATLAS_TEST = "/mnt/nas1/atlas_data/benchmarking/base_atlas_test.npy"

SIZE = 1000

In [32]:
twodarr = np.random.rand(10,10)
twodarr.shape

(10, 10)

In [38]:
twodarr[5, :]

array([0.71583192, 0.04656704, 0.56153946, 0.48158387, 0.42563895,
       0.5427828 , 0.88085468, 0.77722577, 0.16566186, 0.35048947])

In [39]:
twodarr[5]

array([0.71583192, 0.04656704, 0.56153946, 0.48158387, 0.42563895,
       0.5427828 , 0.88085468, 0.77722577, 0.16566186, 0.35048947])

In [3]:
# load the final embeddings
arr = np.load(ATLAS_EMBEDDINGS, allow_pickle=True)

TOTAL_LENGTH = arr.shape[0]


In [4]:
arr_cp = arr
arr_base = arr

In [5]:
TOTAL_LENGTH

32138737

In [6]:
arr.shape

(32138737, 768)

In [7]:

# generate 1000 random index
random.seed(30) # same every time

LST_IND = []
for i in range(SIZE):
    idx = random.randint(0, TOTAL_LENGTH)
    LST_IND.append(idx)
    
np.save(QUERY_INDS_TEST, LST_IND)

In [8]:
arr_lst = []
for idx in LST_IND:
    q_arr = arr[idx]#.reshape(1, 768)
    arr_lst.append(q_arr)
np.save(QUERY_VECS_TEST, arr_lst)

In [21]:
# create base atlas
arr_new = []

for i in tqdm(range(TOTAL_LENGTH)):
    if i not in LST_IND:
        #arr_new = np.take(arr_cp, i)
        arr_new.append(arr[i])

        print("saving base embeddings now.. ")
np.save(BASE_ATLAS_TEST, arr_new)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 32138737/32138737 [03:13<00:00, 166461.75it/s]


In [22]:
# test if query saved

q = np.load(QUERY_VECS_TEST, allow_pickle=True)
idn = np.load(QUERY_INDS_TEST)
base = np.load(BASE_ATLAS_TEST, allow_pickle=True)

In [25]:
base = np.load(BASE_ATLAS, allow_pickle=True)

In [26]:
len(base)

32137737

In [23]:
len(base)

32137737

In [24]:
base.shape

(32137737, 768)

In [56]:
q[0].shape

(768,)

In [61]:
idn.shape

(1000,)

In [16]:
arr_new

-0.01411438

In [18]:
np.take(arr, [0])

array([0.01396942], dtype=float32)

In [19]:
arr[0]

array([ 1.39694214e-02, -1.29928589e-02,  8.77380371e-03,  8.59985352e-02,
       -6.81762695e-02, -1.46713257e-02, -7.66601562e-02, -6.91528320e-02,
        4.65087891e-02, -2.87818909e-03,  3.59191895e-02, -7.22656250e-02,
        6.81762695e-02, -4.49523926e-02, -5.37109375e-02, -1.38549805e-01,
       -2.38189697e-02, -2.96020508e-03, -7.76977539e-02,  1.12548828e-01,
        1.27029419e-02, -1.73950195e-02,  2.54869461e-04,  1.67999268e-02,
        2.14996338e-02, -1.04309082e-01, -3.43322754e-02,  1.06430054e-02,
       -1.78680420e-02, -8.39996338e-03, -1.20468140e-02,  1.83258057e-02,
       -1.08718872e-02, -3.81774902e-02, -5.17883301e-02, -1.07482910e-01,
        7.53784180e-02, -8.17871094e-02,  7.39135742e-02, -6.61621094e-02,
        7.06176758e-02,  1.10168457e-01, -1.14822388e-02, -9.96704102e-02,
        3.43627930e-02, -1.68090820e-01, -4.66613770e-02, -2.07672119e-02,
       -2.40631104e-02, -1.12976074e-01,  1.56860352e-02,  6.53686523e-02,
       -1.02005005e-02, -